# Generated by Django 4.1.2 on 2022-10-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='artiste_id',
            new_name='artiste',
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='artiste_id',
            new_name='artiste',
        ),
    ]
