# Generated by Django 4.1.2 on 2022-10-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_artiste_id_artiste_artiste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='artiste',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='artiste',
        ),
    ]
